import {
  Activity,
  BarChart3,
  Bell,
  BookOpen,
  Brain,
  Calendar,
  ClipboardCheck,
  FileText,
  GraduationCap,
  LayoutDashboard,
  Library,
  MessageCircle,
  Settings,
  Shield,
  Sparkles,
  User,
  Users,
} from "lucide-react";
import { Role } from "../../types";

export const roleNavigation = {
  student: [
    ["Dashboard", "/student/dashboard", LayoutDashboard],
    ["My Courses", "/student/courses", BookOpen],
    ["Subjects", "/student/subjects", Library],
    ["Assignments", "/student/assignments", ClipboardCheck],
    ["Quizzes", "/student/quizzes", FileText],
    ["AI Tutor", "/student/ai-tutor", MessageCircle],
    ["Study Planner", "/student/study-planner", Calendar],
    ["AI Notes", "/student/ai-notes", Brain],
    ["Flashcards", "/student/flashcards", Sparkles],
    ["Recommendations", "/student/recommendations", GraduationCap],
    ["Performance", "/student/performance", BarChart3],
    ["Attendance", "/student/attendance", Activity],
    ["Notifications", "/student/notifications", Bell],
    ["Profile", "/student/profile", User],
    ["Settings", "/student/settings", Settings],
  ],
  teacher: [
    ["Dashboard", "/teacher/dashboard", LayoutDashboard],
    ["My Courses", "/teacher/courses", BookOpen],
    ["Students", "/teacher/students", Users],
    ["Notes", "/teacher/resources", FileText],
    ["Assignments", "/teacher/assignments", ClipboardCheck],
    ["Quizzes", "/teacher/quizzes", FileText],
    ["AI Quiz Generator", "/teacher/ai-generator", Brain],
    ["AI Reports", "/teacher/ai-reports", Sparkles],
    ["Analytics", "/teacher/analytics", BarChart3],
    ["Resources", "/teacher/resources", Library],
    ["Notifications", "/teacher/notifications", Bell],
    ["Profile", "/teacher/profile", User],
    ["Settings", "/teacher/settings", Settings],
  ],
  admin: [
    ["Dashboard", "/admin/dashboard", LayoutDashboard],
    ["Students", "/admin/students", Users],
    ["Teachers", "/admin/teachers", GraduationCap],
    ["Courses", "/admin/courses", BookOpen],
    ["Subjects", "/admin/subjects", Library],
    ["Analytics", "/admin/analytics", BarChart3],
    ["System Activity", "/admin/activity", Activity],
    ["Notifications", "/admin/notifications", Bell],
    ["Settings", "/admin/settings", Shield],
  ],
} as const satisfies Record<Role, readonly (readonly [string, string, React.ElementType])[]>;
